apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: demo
  name: demo


---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: storage
  name: storage

---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: prometheus-operator
  name: prometheus-operator
